### PR TITLE
ui tweaks

### PR DESCRIPTION
**Pull request by PickleNik**
lil diagram of my proposition:
Instead of pulling things from localStorage, UI tweaks are maintained through Vuex.
image

 - keeps changes reactive and reflected throughout the app (the only other option is to setIntervals everywhere or restart the app on every change)
 - keeps code out of individual components as all of the localStorage stuff is done inside Vuex.

NOTE: border radius is disabled by default 😉

### CODE REVIEW

**Comment by PickleNik** [comment]
component code example without vuex:
```
data(){
  return {
      tweakVal: localStorage.getItem('tweakID') || '',
    };
  },
  computed: {
    tweak: {
      get: function() {
        return this.tweakVal;
      },
      set: function(payload) {
        this.tweakVal = payload;
        localStorage.setItem('tweakID', payload)
      }
    }
}
```
component code example with vuex:
```
  computed: {
    roundTweak: {
      get() {
        return this.$store.state.tweaks.roundTweak;
      },
      set(value) {
        this.$store.commit("tweaks/setRoundTweak", value);
      },
    },
  },
```
(the rest is in vuex file)

**Comment by Frontesque** [comment]
I'm not very familiar with VueX so I'll look more into it

**Comment by PickleNik** [comment]
> I'm not very familiar with VueX so I'll look more into it

It's simple, you just keep the kinds of things you would keep in `data ({ })` and all getters and setters for it inside a file under `/store`, and that can be accessed across the app instead of just from 1 component.

**Comment by PickleNik** [comment]
Screen Shot 2022-03-21 at 4 51 22 PM
Screen Shot 2022-03-21 at 4 51 12 PM
latest commit visualized

**Comment by PickleNik** [comment]
Screen Shot 2022-03-21 at 5 22 42 PM
Screen Shot 2022-03-21 at 5 24 48 PM
Screen Shot 2022-03-21 at 5 37 35 PM
latest commit visualized

**Pull request merged**
