### PR TITLE
convert and minify images

### PR DESCRIPTION
**Pull request by JacksonChen666**
700k is a large image (for the web), and so i converted it to jpeg with
imagemagick for best file size (at 100% quality, optimized png is still
larger than converted jpg). other images are just minified.

also changes the link of the image

warning: force push has been used without lease

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
This is...not a great idea. This is literally supposed to be a transparent app icon and you made it a jpeg.

image

**Comment by JacksonChen666** [comment]
i didn't check uhhhh

**Comment by ThatOneCalculator** [comment]
I think having a PR for optimizing images is a bad idea. If you want optimized images, @Frontesque should add [ImgBot](https://github.com/marketplace/imgbot) to this repository and not make humans do this process.

**Comment by ThatOneCalculator** [comment]
@JacksonChen666 with that said, you should probably close this PR. More images will most likely be added in the future, and ImgBot should be taking care of that, not human-made PRs.

**Comment by Frontesque** [comment]
> I think having a PR for optimizing images is a bad idea. If you want optimized images, @Frontesque should add [ImgBot](https://github.com/marketplace/imgbot) to this repository and not make humans do this process.

I've never used imgbot before. Is it just a "plug and play" type thing?

**Comment by ThatOneCalculator** [comment]
> > I think having a PR for optimizing images is a bad idea. If you want optimized images, @Frontesque should add [ImgBot](https://github.com/marketplace/imgbot) to this repository and not make humans do this process.
> 
> I've never used imgbot before. Is it just a "plug and play" type thing?

Apologies for the late reply; yes it's quite literally plug and play. Just go to the link, install it, make sure it's enabled for the repo, and you're done!

**Comment by Frontesque** [comment]
> > > I think having a PR for optimizing images is a bad idea. If you want optimized images, @Frontesque should add [ImgBot](https://github.com/marketplace/imgbot) to this repository and not make humans do this process.
> > 
> > I've never used imgbot before. Is it just a "plug and play" type thing?
> 
> Apologies for the late reply; yes it's quite literally plug and play. Just go to the link, install it, make sure it's enabled for the repo, and you're done!
> 

yea thanks. it's been added :)

**Comment by ThatOneCalculator** [comment]
Awesome! With that done, I think this PR should be closed :)

**Pull request closed without merging**
