### PR TITLE
Update styling and formatting Updates page

### PR DESCRIPTION
**Pull request by lodu**
Still displays all the Git commits however some styling changes:
Before: 
Before

After:
After

### CODE REVIEW

**Comment by Frontesque** [comment]
have you tested this with long commit names and the chips?

**Comment by lodu** [comment]
What do you mean by chips?
Have tested long ass commit messages, they'll just extend the cards as expected (can also be seen in the after screenshot, last update commit).

**Comment by Frontesque** [comment]
> What do you mean by chips?
> Have tested long ass commit messages, they'll just extend the cards as expected (can also be seen in the after screenshot, last update commit).

the chips are the indicators for "latest" and "current" versions

**Comment by lodu** [comment]
Ah yes the tags , I fixed it. Thanks for the pointer/reminder :)
It now dynamically adds a class (has-tag) whenever a condition is met, which causes the title to get 4em; on the right. Not the most elegant solution but I could not get the button to be placed top right without `position absolute` and not breaking other things.

**Comment by lodu** [comment]
Lol weird issue:
image
So its tripping over: `{{ item.author.login }}`
but `item.commit.committer.date` does work.

"login" should exist:
image

Any ideas?

**Comment by lodu** [comment]
Oke I found the problem and fixed it.
As per https://github.community/t/request-for-commits-author-null-and-committer-null-cant-get-user-login/14409/2
not all commits have github accounts associated with them (duhh), so now whenever there is no github login it defaults to `item.commit.author.name` which is better than the commiters name since that can be github.

**Comment by Frontesque** [comment]
this seems like a bigger hastle than it's worth

**Comment by lodu** [comment]
I don't think so, when GH release are being used only the URI and the variable names need to be swapped and its fine.
The `item.author.login` would've gone wrong very soon anyways, so its just unlucky I ran into it.

Pretty sure the CI check failure is not something I can fix.

**Pull request closed without merging**
