### PR TITLE
Improved video playback and browsing in landscape mode

### LINKED ISSUE #110: Status bar
**Describe the bug**
When you're in the app, the status bar stays red and doesn't hide which makes it really intrusive when your watching stuff 

**To Reproduce**
1. Go to 'VueTube'
2. Click on 'a video '
3. Make it full screen

**Expected behavior**
It should be semi transparent and fade away 

**Screenshots**

**Device Information**
 - OS: Android 11
 - App Version dev-loc

Screenshot_20220319-083517
What it looks like in VueTube

Screenshot_20220319-084441
Behaviour in YT Vanced

### PR DESCRIPTION
**Pull request by etekweb**
### Changes

Video player:

- Auto hide navigation bar and status bar when playing video in fullscreen (fixes #110)

Recommended videos:

- Improved landscape browsing experience by collapsing thumbnail image and showing text to its right

### Demonstration

[See video here](https://photos.app.goo.gl/mqJbJVSAhheuqwtBA) (apologies for the aspect ratio, I had to rotate the phone mid-video to demonstrate - probably best to watch in fullscreen)

### CODE REVIEW

**Review by 404-Program-not-found — APPROVED** [review]

**Comment by etekweb** [comment]
I noticed that the updated view for landscape in video lists was not reflected on the search results. I also noticed that search results have a bit different appearance now compared to the recommended video lists (no loading animation, larger thumbnail size, etc.) Since the overall look and function of these results are the same, I integrated search result parsing into the recommended.vue component. To clarify its new purpose, I renamed the component to videoList.vue.

[Here are some images](https://photos.app.goo.gl/PozSWa8Z4Xgtnwqp8) of this change, before and after.

**Comment by 404-Program-not-found** [comment]
> I noticed that the updated view for landscape in video lists was not reflected on the search results. I also noticed that search results have a bit different appearance now compared to the recommended video lists (no loading animation, larger thumbnail size, etc.) Since the overall look and function of these results are the same, I integrated search result parsing into the recommended.vue component. To clarify its new purpose, I renamed the component to videoList.vue.
> 
> [Here are some images](https://photos.app.goo.gl/PozSWa8Z4Xgtnwqp8) of this change, before and after.

Hmm... That might cause some git conflicts with my upcoming PRs since I'm reworking how video elements are rendered to fit more with the actual youtube API

**Comment by Frontesque** [comment]
as @404-Program-not-found has stated, it has some conflicts with the current 'main' branch. It's much better to do a lot of tiny PRs than one big one.

**Comment by etekweb** [comment]
Fair enough, sorry. This is my first open-source project so still trying to figure out the best way to do this, and it's tricky to know what others are working on and avoid those files since we don't have project management. For now, I am going to break this into two separate PRs: one for fixing the fullscreen, and another for landscape thumbnails, and pull from main for each beforehand. Those will be incoming shortly.

**Pull request closed without merging**
